# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rc-hackathon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rchackathon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bdbe8157043043da98b34c1d0b5c42c4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bcfa50a0eb3f451ea276915b5923ab04 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rchackathon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdbe8157043043da98b34c1d0b5c42c4 }}/express-rc-hackathon:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rc-hackathon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0e2c1d7a3ad748d1aca554187811518a }}
        images: 'rchackathon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bdbe8157043043da98b34c1d0b5c42c4 }}/express-rc-hackathon:${{ github.sha }}'