# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rchackathon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://rchackathon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e24b7eeccd94377af1e99eebfe24d5a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6353bb946db74cdf90ba4acacdeb5ef7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rchackathon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5e24b7eeccd94377af1e99eebfe24d5a }}/express-rc-hackathon-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rchackathon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f5c8ae3940d4b9d8d7a62e450039507 }}
        images: 'rchackathon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5e24b7eeccd94377af1e99eebfe24d5a }}/express-rc-hackathon-server:${{ github.sha }}'